services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
    - CHOKIDAR_USEPOLLING=true  # Enables hot reloading
    - WATCHPACK_POLLING=true     # Helps detect file changes

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
